{{- if .Values.enabled }}
{{- if and .Values.document_process.serviceAccount.enabled .Values.document_process.serviceAccount.role.create .Values.document_process.serviceAccount.role.rules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helper.componentFullname" (dict "root" . "componentName" "document_process") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "document_process")) | nindent 4 }}
rules: {{- toYaml .Values.document_process.serviceAccount.role.rules | nindent 0 }}
{{- end }}
{{- end }}
