{{- if .Values.enabled }}
{{- if eq .Values.document_process.deploymentType "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "helper.componentFullname" (dict "root" . "componentName" "document_process") }}
  labels: {{- include "helper.labels" (dict "root" . "componentName" "document_process") | nindent 4 }}
spec:
  {{- if not .Values.document_process.autoscaling.enabled }}
  replicas: {{ .Values.document_process.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.document_process.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "document_process") | nindent 6 }}
  serviceName: {{ include "helper.componentFullname" (dict "root" . "componentName" "document_process") }}
  {{- with .Values.document_process.updateStrategy }}
  updateStrategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    {{- include "helper.component.podTemplate" (dict "root" . "name" "document_process" "component" .Values.document_process) | nindent 4 }}
  {{- if or .Values.document_process.volumeClaims .Values.document_process.extraVolumeClaims }}
  volumeClaimTemplates: {{- toYaml (concat (default (list) .Values.document_process.volumeClaims) (default (list) .Values.document_process.extraVolumeClaims)) | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
