{{- if .Values.enabled }}
{{- if eq .Values.agent_execution.deploymentType "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "helper.componentFullname" (dict "root" . "componentName" "agent_execution") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "agent_execution")) | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.agent_execution.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "agent_execution") | nindent 6 }}
  {{- with .Values.agent_execution.updateStrategy }}
  updateStrategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    {{- include "helper.component.podTemplate" (dict "root" . "name" "agent_execution" "component" .Values.agent_execution) | nindent 4 }}
{{- end }}
{{- end }}
