{{- if .Values.enabled }}
{{- if or .Values.agent_execution.envSecret .Values.global.envSecret -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "helper.componentFullname" (dict "root" . "componentName" "agent_execution") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "agent_execution")) | nindent 4 }}
data:
  {{- if .Values.global.envSecret -}}
  {{- include "helper.secret" (dict "root" . "data" .Values.global.envSecret) | indent 2 }}
  {{- end -}}
  {{- if .Values.agent_execution.envSecret -}}
  {{- include "helper.secret" (dict "root" . "data" .Values.agent_execution.envSecret) | indent 2 }}
  {{- end -}}
{{- end -}}
{{- end }}
