"""add run edit proposal and requester snapshot

Revision ID: 4cdf987deaf9
Revises: 2453641a8e9f
Create Date: 2026-10-08 23:39:31.437220

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4cdf987deaf9"
down_revision: str | Sequence[str] | None = "2453641a8e9f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("user_is_admin", sa.Boolean(), server_default="false", nullable=False))
    op.add_column("runs", sa.Column("user_display", sa.String(), nullable=True))
    op.add_column("runs", sa.Column("edit_proposal", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "edit_proposal")
    op.drop_column("runs", "user_display")
    op.drop_column("runs", "user_is_admin")
    # ### end Alembic commands ###
