"""add worker fields: document storage_key, page screenshot, chunk extras

Revision ID: 789d7fc786d5
Revises: 18103bc9f998
Create Date: 2026-09-17 00:16:03.557929

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "789d7fc786d5"
down_revision: str | Sequence[str] | None = "18103bc9f998"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunks", sa.Column("extras", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("document_pages", sa.Column("screenshot", sa.String(), nullable=True))
    op.add_column("documents", sa.Column("storage_key", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "storage_key")
    op.drop_column("document_pages", "screenshot")
    op.drop_column("chunks", "extras")
    # ### end Alembic commands ###
