"""add instructions_summary and pipeline_windows to collection_settings

Revision ID: 02ab8ea16bbb
Revises: ccc2c83495f1
Create Date: 2026-09-17 06:19:03.416824

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "02ab8ea16bbb"
down_revision: str | Sequence[str] | None = "ccc2c83495f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default, not just the model's Python-side default: this column
    # is NOT NULL and the table already has rows (unlike the initial
    # migration's CREATE TABLE, which started empty).
    op.add_column(
        "collection_settings", sa.Column("instructions_summary", sa.Text(), nullable=False, server_default="")
    )
    op.add_column(
        "collection_settings", sa.Column("pipeline_windows", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection_settings", "pipeline_windows")
    op.drop_column("collection_settings", "instructions_summary")
    # ### end Alembic commands ###
