"""add collection visibility and hashed collection shares

Revision ID: 41712b4708f0
Revises: d4e5f6a7b8c9
Create Date: 2026-09-18 23:00:42.789431

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41712b4708f0"
down_revision: str | Sequence[str] | None = "d4e5f6a7b8c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


share_status_enum = sa.Enum("PENDING", "ACTIVE", name="share_status")
collection_visibility_enum = sa.Enum("PRIVATE", "PUBLIC", name="collection_visibility")


def upgrade() -> None:
    """Upgrade schema."""
    # New enum types aren't auto-created by ADD COLUMN the way CREATE TABLE would - must create
    # them explicitly first.
    share_status_enum.create(op.get_bind(), checkfirst=True)
    collection_visibility_enum.create(op.get_bind(), checkfirst=True)

    # server_default on every NOT NULL column added below: collection_shares has never been
    # wired to any code path so it's empty in practice, and collections is very much not empty -
    # adding a NOT NULL column without one would fail outright against a real deployment.
    op.add_column(
        "collection_shares",
        sa.Column("status", share_status_enum, nullable=False, server_default="PENDING"),
    )
    op.add_column("collection_shares", sa.Column("invited_identifier_hash", sa.String(), nullable=True))
    op.add_column("collection_shares", sa.Column("display_hint", sa.String(), nullable=False, server_default=""))
    op.alter_column("collection_shares", "subject_id", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(
        op.f("ix_collection_shares_invited_identifier_hash"),
        "collection_shares",
        ["invited_identifier_hash"],
        unique=False,
    )
    op.create_index(op.f("ix_collection_shares_status"), "collection_shares", ["status"], unique=False)
    op.create_unique_constraint(
        "uq_collection_share_active_subject", "collection_shares", ["collection_id", "subject_type", "subject_id"]
    )
    op.create_unique_constraint(
        "uq_collection_share_pending_identifier",
        "collection_shares",
        ["collection_id", "subject_type", "invited_identifier_hash"],
    )
    op.add_column(
        "collections",
        sa.Column("visibility", collection_visibility_enum, nullable=False, server_default="PRIVATE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collections", "visibility")
    op.drop_constraint("uq_collection_share_pending_identifier", "collection_shares", type_="unique")
    op.drop_constraint("uq_collection_share_active_subject", "collection_shares", type_="unique")
    op.drop_index(op.f("ix_collection_shares_status"), table_name="collection_shares")
    op.drop_index(op.f("ix_collection_shares_invited_identifier_hash"), table_name="collection_shares")
    op.alter_column("collection_shares", "subject_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("collection_shares", "display_hint")
    op.drop_column("collection_shares", "invited_identifier_hash")
    op.drop_column("collection_shares", "status")
    # ### end Alembic commands ###

    collection_visibility_enum.drop(op.get_bind(), checkfirst=True)
    share_status_enum.drop(op.get_bind(), checkfirst=True)
