"""add living documents and document revisions

Revision ID: 4f7b9d8801e4
Revises: 91fd1c728c90
Create Date: 2026-10-08 18:41:49.972169

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4f7b9d8801e4"
down_revision: str | Sequence[str] | None = "91fd1c728c90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# add_column (unlike create_table) doesn't create the enum type it uses, so it's created
# explicitly first and then referenced with create_type=False.
document_kind_enum = postgresql.ENUM("STANDARD", "LIVING", name="document_kind", create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    document_kind_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_revisions",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("origin", sa.Enum("UPLOAD", "CHAT", "UI", "RESTORE", name="revision_origin"), nullable=False),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("created_by_display", sa.String(), nullable=True),
        sa.Column("restored_from_number", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "number", name="uq_document_revisions_document_number"),
    )
    op.create_index(op.f("ix_document_revisions_document_id"), "document_revisions", ["document_id"], unique=False)
    op.add_column(
        "documents",
        sa.Column("kind", document_kind_enum, server_default="STANDARD", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "kind")
    op.drop_index(op.f("ix_document_revisions_document_id"), table_name="document_revisions")
    op.drop_table("document_revisions")
    # ### end Alembic commands ###

    # drop_column/drop_table don't drop the enum types they used - explicit cleanup so a
    # re-upgrade doesn't hit "type already exists" (same pattern as other enum-backed migrations).
    sa.Enum(name="revision_origin").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="document_kind").drop(op.get_bind(), checkfirst=True)
