"""add reports table

Revision ID: 91fd1c728c90
Revises: 142eabf70756
Create Date: 2026-09-22 10:12:32.859478

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91fd1c728c90"
down_revision: str | Sequence[str] | None = "142eabf70756"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


report_type_enum = sa.Enum("BUG", "IDEA", "QUESTION", name="report_type")
report_status_enum = sa.Enum("NEW", "IN_PROGRESS", "RESOLVED", "WONT_FIX", name="report_status")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("user_display", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("BUG", "IDEA", "QUESTION", name="report_type"), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Enum("NEW", "IN_PROGRESS", "RESOLVED", "WONT_FIX", name="report_status"), nullable=False
        ),
        sa.Column("screenshot_key", sa.String(), nullable=True),
        sa.Column("admin_response", sa.Text(), nullable=True),
        sa.Column("responded_by", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_user_id"), "reports", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_user_id"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###

    # drop_table doesn't drop the enum types it used - explicit cleanup so a re-upgrade doesn't
    # hit "type already exists" (same pattern as other enum-backed migrations in this repo).
    report_status_enum.drop(op.get_bind(), checkfirst=True)
    report_type_enum.drop(op.get_bind(), checkfirst=True)
