"""add living document edit lock

Revision ID: d08dc97b5ff9
Revises: 4f7b9d8801e4
Create Date: 2026-10-08 18:59:44.132195

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d08dc97b5ff9"
down_revision: str | Sequence[str] | None = "4f7b9d8801e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("lock_token", sa.String(), nullable=True))
    op.add_column("documents", sa.Column("locked_by_user_id", sa.String(), nullable=True))
    op.add_column("documents", sa.Column("locked_by_display", sa.String(), nullable=True))
    op.add_column("documents", sa.Column("lock_expires_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "lock_expires_at")
    op.drop_column("documents", "locked_by_display")
    op.drop_column("documents", "locked_by_user_id")
    op.drop_column("documents", "lock_token")
    # ### end Alembic commands ###
