"""add task parent/logs and document error columns

Revision ID: bd4dc87d7efa
Revises: 927645173e27
Create Date: 2026-09-17 07:01:03.281724

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd4dc87d7efa"
down_revision: str | Sequence[str] | None = "927645173e27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("error", sa.Text(), nullable=True))
    op.add_column("tasks", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.add_column("tasks", sa.Column("logs", sa.Text(), nullable=True))
    op.create_foreign_key("fk_tasks_parent_id_tasks", "tasks", "tasks", ["parent_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_tasks_parent_id_tasks", "tasks", type_="foreignkey")
    op.drop_column("tasks", "logs")
    op.drop_column("tasks", "parent_id")
    op.drop_column("documents", "error")
    # ### end Alembic commands ###
