"""add document drafts

Revision ID: 2453641a8e9f
Revises: d08dc97b5ff9
Create Date: 2026-10-08 22:59:17.486414

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2453641a8e9f"
down_revision: str | Sequence[str] | None = "d08dc97b5ff9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_drafts",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("base_revision", sa.Integer(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "READY", "FAILED", name="draft_status"), nullable=False),
        sa.Column("job_kind", sa.String(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("requested_by_user_id", sa.String(), nullable=False),
        sa.Column("requested_by_display", sa.String(), nullable=True),
        sa.Column("celery_task_id", sa.String(), nullable=True),
        sa.Column("lock_token", sa.String(), nullable=False),
        sa.Column("draft_storage_key", sa.String(), nullable=True),
        sa.Column("preview_pdf_key", sa.String(), nullable=True),
        sa.Column("operations_summary", sa.Text(), server_default="", nullable=False),
        sa.Column("edited", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("pending_images", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_drafts_celery_task_id"), "document_drafts", ["celery_task_id"], unique=True)
    op.create_index(op.f("ix_document_drafts_document_id"), "document_drafts", ["document_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_drafts_document_id"), table_name="document_drafts")
    op.drop_index(op.f("ix_document_drafts_celery_task_id"), table_name="document_drafts")
    op.drop_table("document_drafts")
    # ### end Alembic commands ###

    # drop_table doesn't drop the enum type it used - explicit cleanup so a re-upgrade doesn't hit
    # "type already exists" (same pattern as other enum-backed migrations).
    sa.Enum(name="draft_status").drop(op.get_bind(), checkfirst=True)
