"""add runs and run_events tables

Revision ID: 3632c0e81a2a
Revises: a378c3ad577e
Create Date: 2026-09-17 11:03:02.259919

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3632c0e81a2a"
down_revision: str | Sequence[str] | None = "a378c3ad577e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("celery_task_id", sa.String(), nullable=True),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "WAITING_FOR_USER",
                "REPLANNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="run_status",
            ),
            nullable=False,
        ),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("current_node", sa.String(), nullable=True),
        sa.Column("current_activity", sa.String(), nullable=True),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("replan_count", sa.Integer(), nullable=False),
        sa.Column("research_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("budget", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pending_human_action", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_celery_task_id"), "runs", ["celery_task_id"], unique=True)
    op.create_index(op.f("ix_runs_conversation_id"), "runs", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_runs_message_id"), "runs", ["message_id"], unique=True)
    op.create_index(op.f("ix_runs_user_id"), "runs", ["user_id"], unique=False)
    op.create_table(
        "run_events",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_events_run_id"), "run_events", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_events_run_id"), table_name="run_events")
    op.drop_table("run_events")
    op.drop_index(op.f("ix_runs_user_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_message_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_conversation_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_celery_task_id"), table_name="runs")
    op.drop_table("runs")
    # ### end Alembic commands ###
