"""add standalone filing holding collections and top-k suggestions

Revision ID: 0e2dfb8a4e41
Revises: de60b21ac164
Create Date: 2026-09-21 23:51:42.253999

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0e2dfb8a4e41"
down_revision: str | Sequence[str] | None = "de60b21ac164"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_collections_owner_holding",
        "collections",
        ["owner_id"],
        unique=True,
        postgresql_where=sa.text("is_temporary IS true AND conversation_id IS NULL"),
    )
    op.add_column("documents", sa.Column("filing_candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "filing_candidates")
    op.drop_index(
        "uq_collections_owner_holding",
        table_name="collections",
        postgresql_where=sa.text("is_temporary IS true AND conversation_id IS NULL"),
    )
    # ### end Alembic commands ###
