"""add web_search_enabled to runs

Revision ID: 9c08ea420680
Revises: b2e1c851b57c
Create Date: 2026-09-19 09:44:21.831597

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c08ea420680"
down_revision: str | Sequence[str] | None = "b2e1c851b57c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default: runs already has rows in a real deployment - a NOT NULL column without one
    # would fail outright, same reasoning as every other NOT NULL column added post-launch here.
    op.add_column("runs", sa.Column("web_search_enabled", sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "web_search_enabled")
    # ### end Alembic commands ###
