"""drop collection_description_embeddings, now indexed in Meilisearch only

Revision ID: 88c0e06ef234
Revises: 3e2a4a8c7bec
Create Date: 2026-09-21 23:06:19.065450

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88c0e06ef234"
down_revision: str | Sequence[str] | None = "3e2a4a8c7bec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collection_description_embeddings")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_description_embeddings",
        sa.Column("collection_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("model", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("embedding", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("collection_description_embeddings_collection_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("collection_id", name=op.f("collection_description_embeddings_pkey")),
    )
    # ### end Alembic commands ###
