"""add generation_models to collection_settings

Revision ID: ccc2c83495f1
Revises: 789d7fc786d5
Create Date: 2026-09-17 05:51:14.357623

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ccc2c83495f1"
down_revision: str | Sequence[str] | None = "789d7fc786d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection_settings", sa.Column("generation_models", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection_settings", "generation_models")
    # ### end Alembic commands ###
